### PR TITLE
Create UserProfileTest.java

### PR DESCRIPTION
**Pull request by ARWA-ALraddadi**

### CODE REVIEW

**Comment by ezeutno** [comment]
@ARWA-ALraddadi please re-check your code I think there is problem in compile level. You could check it using the Details on Maven Test Ci

**Comment by ezeutno** [comment]
@ARWA-ALraddadi 
image
There's a problem in it's building process

**Comment by kyemurf** [comment]
try changing changing

public BookingAreaTest() {
}

to

private BookingArea testSubject;

**Comment by kyemurf** [comment]
Add these lines back in to the code this should help 

@Before   
 public void setUp() throws Exception {        this.testSubject = new BookingArea();  
  }

@After    
public void tearDown() throws Exception{        
testSubject = null; 
  }

**Pull request closed without merging**
